spring:
  datasource:
    url: jdbc:mysql://localhost:3360/users
    username: root
    password: jvman19
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        TYPE: TRACE

